on:
  push:
    branches:
      - main
      - develop

name: Deploy and Slack Notification
jobs:
  deploy:
    name: Deploy
    # Change below line to: `runs-on: ubuntu-latest` if not using self-hosted runners or if it is a public repo.
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      uses: rtCamp/action-deploy-wordpress@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        WP_VERSION: latest
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: test
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
